---
Name: permanentinc-found
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - permanentinc/found:dist\scss\style.css
  extra_requirements_javascript:
    - permanentinc/found:dist\js\app.js

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - permanentinc\found\Extensions\FoundExtension

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - permanentinc\found\Extensions\FoundConfigExtension

permanentinc\found\extensions:
  extensions:
    - permanentinc\found\Extensions\FoundAjaxExtension

SilverStripe\Control\Director:
  rules:
    "foundAPI//$Method": permanentinc\found\Extensions\FoundAjaxExtension